using AspNetCoreRateLimit;
using SpyderByteResources.Extensions;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers().ConfigureApiBehaviorOptions(options => options.SuppressMapClientErrors = true);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddProjectVersioning(builder.Configuration);
builder.Services.AddProjectDependencies();
builder.Services.AddProjectDatabase(builder.Configuration);
builder.Services.AddHttpClient();
builder.Services.AddProjectCors();
builder.Services.AddProjectAzureServices(builder.Configuration);
builder.Services.AddMemoryCache();
builder.Services.AddProjectRateLimiting();
builder.Services.AddProjectMapperProfiles();
builder.Services.AddProjectAuthentication(builder.Configuration);
builder.Services.AddProjectAuthorization();
builder.Services.AddProjectFeatureFlags(builder.Configuration);

var app = builder.Build();
app.AddSwaggerConfiguration(builder.Configuration);
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.UseCors("SpyderByteAPIOrigins");
app.UseIpRateLimiting();
app.AddProjectMiddleware();
app.RunProjectMigrations();
app.Run();