name: Azure FTP Deployment

env:
  AZURE_WEBAPP_NAME: SpyderByteAPI-AppService
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.x'

on:
  push:
    branches: [ "prod" ]
  workflow_dispatch:

permissions:
  contents: read
    
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to Azure
      run: |
        az login --username olivernicholls91@hotmail.com --password ${{ secrets.ADMIN_PASSWORD }}
        
    - name: Restart web app to unlock files
      run: |
        az webapp restart --resource-group SpyderByteAPI-ResourceGroup --name SpyderByteAPI-AppService
  
    - name: Checkout latest code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build with dotnet
      run: dotnet build --target:SpyderByteAPI --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release --property:PublishDir=${{env.DOTNET_ROOT}}/myapp
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: waws-prod-blu-343.ftp.azurewebsites.windows.net
        server-dir: site/wwwroot/
        local-dir: ${{env.DOTNET_ROOT}}/myapp/
        username: SpyderByteAPI-AppService\SpyderByteAPI-AppService-FTPS
        password: ${{ secrets.FTP_PASSWORD }}
