name: Azure FTP Deployment

env:
  AZURE_WEBAPP_NAME: SpyderByteAPI-AppService
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.x'

on:
  push:
    branches: [ "prod" ]
    
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v4

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release --property:PublishDir=${{env.DOTNET_ROOT}}/PubOut
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: waws-prod-blu-343.ftp.azurewebsites.windows.net
        server-dir: site/wwwroot/
        local-dir: ./PubOut
        username: SpyderByteAPI-AppService\SpyderByteAPI-AppService-FTPS
        password: ${{ secrets.FTP_PASSWORD }}
