name: Restart Azure Web App

on:
  workflow_dispatch:
    
jobs:
  restart:
    runs-on: windows-latest
    
    steps:
    - name: Login to Azure as Service Principal.
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart Azure web app to unlock resources.
      shell: pwsh
      with:
        inlineScript: |
          az webapp restart --resource-group SpyderByteAPI-ResourceGroup --name SpyderByteAPI-AppService

    - name: Give the Azure Web App time to wake up.
      shell: pwsh
      run: Start-Sleep -Seconds 10